client_id: '7'
fitting_configs:
  logging_id: "FedFit_SiteMakhatini"
  logging_output_dirname: "/u/parthpatel7173/MMA_RadioWave/FederatedFitting/examples/output"
  logging_output_filename: "pf_8sites_distributed_day50_run3"

  dataset_path: "/u/parthpatel7173/MMA_RadioWave/FederatedFitting/examples/fitting_dataset/Makhatini_data.csv"
  # Path to save local results
  save_folder: "/u/parthpatel7173/MMA_RadioWave/FederatedFitting/examples/results/pf_8sites_distributed_day50_run3/Makhatini/"
  run_name: pf_8sites_distributed_day50_run3
  plot_names: GW170817_pf_8sites_distributed_day50_run3
  
comm_configs:
  octopus_configs:
      topic: 'MMA_RW_FedFit_Events_run14'
      group_id: 'mma-RW-FedFit-site7-run14'

  proxystore_configs:
      enable_proxystore: True
      # connector_type: "EndpointConnector"
      # connector_configs:
      #   endpoints: ["b9161509-0af5-4f5b-8541-75550afa95bd","c7b0e638-2284-420a-83e7-c9d007881a60"]
        #detector1 endpoint, server endpoint
        
      connector_type: "FileConnector"
      connector_configs:
        store_dir: "/scratch/bcbw/parthpatel7173/proxystore"