client_id: '1'
fitting_configs:
  logging_id: "FedFit_Site1"
  logging_output_dirname: "<absolute path to repo>/examples/output"
  logging_output_filename: "result"

  dataset_path: "<absolute path to downloaded data directory>/Inference_dataset/GW200129_065458_1264314069.hdf5"

comm_configs:
  octopus_configs:
      topic: 'MMA_RW_FedFit_Events'
      group_id: 'mma-RW-FedFit-site1'
