client_id: '1'
fitting_configs:
  logging_id: "FedFit_Site1"
  logging_output_dirname: "<absolute path to repo>/examples/output"
  logging_output_filename: "result"

  dataset_path: "<absolute path to downloaded data directory>/Inference_dataset/GW200129_065458_1264314069.hdf5"

  # Path to save local results
  save_folder: "<absolute path to repo>/examples/results/with_ini_polaris_consenses_2ndrun/"
  run_name: example
  plot_names: GW170817

comm_configs:
  octopus_configs:
      topic: 'MMA_RW_FedFit_Events'
      group_id: 'mma-RW-FedFit-site1'

  proxystore_configs:
      enable_proxystore: True
      # connector_type: "EndpointConnector"
      # connector_configs:
      #   endpoints: ["b9161509-0af5-4f5b-8541-75550afa95bd","c7b0e638-2284-420a-83e7-c9d007881a60"]
        #detector1 endpoint, server endpoint
        
      connector_type: "FileConnector"
      connector_configs:
      store_dir: "/scratch/bcbw/parthpatel7173/proxystore"