client_id: '0'
fitting_configs:
  logging_id: "FedFit_Site0"
  logging_output_dirname: "/u/parthpatel7173/MMA_RadioWave/FederatedFitting/examples/output"
  logging_output_filename: "result"

  dataset_path: "/u/parthpatel7173/MMA_RadioWave/FederatedFitting/examples/fitting_dataset/GW170817_data/Makhatini2021Data_site1.csv"
  # Path to save local results
  save_folder: "/u/parthpatel7173/MMA_RadioWave/FederatedFitting/examples/results/distributed_site1/"
  run_name: example
  plot_names: GW170817
  
comm_configs:
  octopus_configs:
      topic: 'MMA_RW_FedFit_Events'
      group_id: 'mma-RW-FedFit-site0'

  proxystore_configs:
      enable_proxystore: True
      # connector_type: "EndpointConnector"
      # connector_configs:
      #   endpoints: ["b9161509-0af5-4f5b-8541-75550afa95bd","c7b0e638-2284-420a-83e7-c9d007881a60"]
        #detector1 endpoint, server endpoint
        
      connector_type: "FileConnector"
      connector_configs:
        store_dir: "/scratch/bcbw/parthpatel7173/proxystore"