client_configs:
  fitting_configs:
    use_approach: "2"
    resilience_testing: True  # if true skip data points between day 60 and day 200 and use remaining days of data to fit light curve
  
  # initial_guess:
  #   # Troja 2020
  #   "jetType": grb.jet.Gaussian
  #   "specType": 0
  #   "thetaObs": 0.54
  #   "E0": 1e53
  #   "thetaCore": 0.088
  #   "thetaWing": 0.6
  #   "n0": 2e-2
  #   "p": 2.139
  #   "epsilon_e": 0.01
  #   "epsilon_B": 2e-4
  #   "xi_N": 1.0
  #   "d_L": 1.2344e26
  #   "z": 0.00897

  mcmc_configs:
    nwalkers: 32
    niters: 2000
    burnin: 500

    # random_seed: 12345
    random_seed: 981721
    #If Z is known, set Z_known = True and give its value. It will not be included in the smapling proceedure.
    Z_known: True
    Z_range: [.001,8]
    Z_fixed: 0.00980

    #If DL is known, set DL_known = True and give its value. It will not be included in the smapling proceedure.
    #DL_range should be the output of Dingo, in Mpc (will convert internally to cm)

    DL_known: False
    # Dingo 90% CI
    # DL_range: [18.532, 45.399]
    # Dingo 68% CI
    DL_range: [24.079, 43.153]
    DL_fixed: 40

    #thetaObs is observing angle in radians (0, pi/2)
    # thetaObs_range: [0,1.571] 

    # thetaObs from Dingo 90%CI
    # thetaObs_range: [0.227, 1.190] 

    # 68 % CI
    thetaObs_range: [0.401, 1.073]

    # Values taken from paper: A thousand days after the merger: Continued X-ray emission from GW170817
    epsilon_e_fixed: 0.01  # loge = -2.0
    epsilon_b_fixed: 0.0002 #logb = -3.7
    thetacore_fixed: 0.088
    thetawing_fixed: 0.6
    p_fixed: 2.139

    #thetaCore is observing angle in radians (0, 10 deg) 
    thetaCore_range: [0,.1745]

    #P the electron distribution index 
    P_range: [2.01,2.5]

    #thetaCore is observing angle in radians (10, 45 deg) 
    thetaWing_range: [.1745,.7854]

    #logE0 is log10 central energy of the jet 
    logE0_range: [48,54]

    #logn0 is log10 ism density (1/cm^3)
    logn0_range: [-5,2]

    #logEpsilon_e log10 fraction of energy given to the electrons
    logEpsilon_e_range: [-5,-.5]

    #logEpsilon_e log10 fraction of energy given to the B feild
    logEpsilon_B_range: [-5,-.5]

    #whether to include the upper limits on the LC plot (they are never included in the fit)
    include_upper_limits_on_lc: True

    #exclude data for which the time, RA, and Dec are not included?
    exclude_time_flag: False
    exclude_ra_dec_flag: False
    exclude_name_flag: False

    #exclude data which reports a different target than the one named?
    exclude_wrong_name: False
    name_of_source: "SSS17a"
    GPS_time_of_GW: 123456789
    ra: 13h09m48.085s
    dec: -23d22m53s

    #whether or not we exclude data outside of the radius
    exclude_outside_ra_dec_uncertainty: False

    #the radius outside of which we reject
    arcseconds_uncertainty: 10

    #whether or not to include the truth valueson the corner plots
    display_truths_on_corner: True
    # order of params ['log(E0)','thetaObs','thetaCore','log(n0)','log(eps_e)','log(eps_B)','p', 'thetaWing', 'z', 'DL']
    # true_values: [53, .54, 0.088, -1.699, -2, -3.699, 2.139, 0.6, 0.0098, 40]
    
    # order params = ['log(E0)','thetaObs','log(n0)', 'DL']  # REMOVED thetaCore, p, thetaWing
    true_values: [53, .54, -1.7, 40]
    # took above values from a table in paper


  comm_configs:
    # octopus_configs:
    compressor_configs:
      enable_compression: False

server_configs:
  aggregator_kwargs:
    num_clients: 8
    # directory to store results after consensus/aggregation/sum of log-likelihood
    save_folder: "/u/parthpatel7173/MMA_RadioWave/FederatedFitting/examples/results/pf_8sites_distributed_dayAll_resilientrun4/"
    run_name: "pf_8sites_distributed_dayAll_resilientrun4"
    plot_names: "GW170817_pf_8sites_distributed_dayAll_resilientrun4"
    
    # #whether or not to include the truth valueson the corner plots
    # display_truths_on_corner: "True"
    # true_values: [53, .54, 0.088, -1.699, -2, -3.699, 2.139, 0.6, 0.00897]

  logging_output_dirname: "/u/parthpatel7173/MMA_RadioWave/FederatedFitting/examples/output"
  logging_output_filename: "pf_8sites_distributed_dayAll_resilientrun4"

  # define server side kafka parameters here like consumer settings (offset policy)
  # Fedfit module listens to overlap analysis messages from MMA module as well topic and post it to another topic fedfit topic to interact with clients/sites
  comm_configs:
    octopus_configs:
      # mma_topic:
      #   topic: 'MMA_Module_Events'
      #   group_id: 'mma-RW-FedFit-server'
      # fedfit_topic:
      topic: 'MMA_RW_FedFit_Events_run14'
      group_id: 'mma-RW-FedFit-server-run14'
