bns_parameter_estimation_configs:

  logging_output_dirname: "/lus/eagle/projects/RAPINS/parth/MMA_RadioWave/ParameterEstimation/examples/output"
  logging_output_filename: "estimatorlogHL"
  
  # define Octopus kafka parameters here like consumer settings (offset policy)
  # Parameter estimator listens to radio events topic for gcn with bnsprob>0.5 and post it to another topic -- mma topic
  comm_configs:
    octopus_configs:
      mma_topic:
        topic: 'MMA_Module_Events'
        # group_id: 'mma-RW-GCN-listener'
      radio_topic:
        topic: 'MMA_RW_Module_Events'
        group_id: 'mma-RW-Estimator'
    

  # Directory for downloading trained Dingo-BNS model and the measured data (a noise PSD and a GW strain file for each of the three detectors H1,  L1, V1)
  downloader_configs:
    download_dir: "/lus/eagle/projects/RAPINS/parth/MMA_RadioWave/ParameterEstimation/examples/inference_data/GW170817_data"

  dingo_configs:
    # Ensure you provide the correct data path in ini. It should be same as where you download the data (data_dir paramter above)
    ini_filepath: "/lus/eagle/projects/RAPINS/parth/MMA_RadioWave/ParameterEstimation/examples/configs/GW170817_repo.ini"
    # Path to results directory - where we save corner plots
    result_dir: "./outdir_HL_det/result/"
    # Path to HDF5 result from Dingo
    samples_filepath: "./outdir_HL_det/result/GW170817_data0_1187008882-42_importance_sampling.hdf5"